language: node_js
node_js:
- '8'
script:
- npm install
- npm run lint
- npm test
- npm run build
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: 0ffbbfae-512d-4307-9908-400819f80bcf
notifications:
  slack:
    secure: ZN3sOb25Aec3W79/Uvj4BwohbmUej3Cgy1+P8p4n3pYmkVEEkLhIZWL1R+RBPoCUcd66lKvbwzB8016XYNamzTa2ma7+DGr6WBTz3Q9eD8y0zvCPSgrVgGBATgFzMoJGlt+d3yzH6ExDQzq081oRnSbgkyj7L/UuAbiOUitn2Eif5pO6r4Lwr3tJcwEZUdyU7kTNhc1Cue8IwwcCCWH/yEd7R7GOjAvPUVdxVHLt3q7Uz+9sKWU26z8HH9zef2KI7ACSdUe1FpI8r4o4gUfMKJyywn7A1Z+wS11lxwgOLPQReP1CKZv1XEWZAmGfx8114+9q5W6ctIZyN174YX5n6EDabWQ4LZUXzvgRjoIUCkmjykY7bZcHz/hXuUnHUEzj8xBK9FdYO6uZ9pq2YDg6uo2sVZkDRKxeixpBUlrmXYWskIT3KypKolm7dtVQ0rHmDv/iUhi5kTuNNOrrzOjvj1ZB/0CBMlTaiho5LLgbqDRhVhYkk750drsp1Bj+nApaqhkIIoqS6jQqf1aYMGfDDniCVDX77bFkAuTubI/C4pzMHuOZwpfjpoQp91mt0miwlv7iyQ6mvlQ2NyaNd+5G47ZkuCFLTG3R0tmjeyFUGTPsG28jk9khvz2/BDrmMXChNM+H93Vm9WYAq0Z6ANq9wxsqRGn6bEse+fHIQWUBx0A=
