language: node_js
node_js:
  - "8"

script:
  - npm install
  - npm run lint
  - npm run build
  - npm test

branches:
  only:
    - master

deploy:
  provider: heroku
  api_key:
    secure: "0ffbbfae-512d-4307-9908-400819f80bcf"